-- MySQL Script generated by MySQL Workbench
-- 05/12/20 22:47:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EMOCIONAL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EMOCIONAL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EMOCIONAL` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `EMOCIONAL` ;

-- -----------------------------------------------------
-- Table `EMOCIONAL`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMOCIONAL`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `EMOCIONAL`.`Usuario` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Username` VARCHAR(45) NULL COMMENT '',
  `Password` VARCHAR(45) NULL COMMENT '',
  `Sexo` VARCHAR(25) NULL COMMENT '',
  PRIMARY KEY (`IdUsuario`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `EMOCIONAL`.`EstadoDoctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMOCIONAL`.`EstadoDoctor` ;

CREATE TABLE IF NOT EXISTS `EMOCIONAL`.`EstadoDoctor` (
  `idEstadoDoctor` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Estado` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idEstadoDoctor`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMOCIONAL`.`Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMOCIONAL`.`Doctor` ;

CREATE TABLE IF NOT EXISTS `EMOCIONAL`.`Doctor` (
  `IdDoctor` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombres` VARCHAR(45) NULL COMMENT '',
  `Apellidos` VARCHAR(45) NULL COMMENT '',
  `Identificacion` VARCHAR(45) NULL COMMENT '',
  `Username` VARCHAR(45) NULL COMMENT '',
  `Password` VARCHAR(45) NULL COMMENT '',
  `Estado` VARCHAR(45) NULL COMMENT '',
  `EstadoDoctor_idEstadoDoctor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdDoctor`, `EstadoDoctor_idEstadoDoctor`)  COMMENT '',
  INDEX `fk_Doctor_EstadoDoctor1_idx` (`EstadoDoctor_idEstadoDoctor` ASC)  COMMENT '',
  CONSTRAINT `fk_Doctor_EstadoDoctor1`
    FOREIGN KEY (`EstadoDoctor_idEstadoDoctor`)
    REFERENCES `EMOCIONAL`.`EstadoDoctor` (`idEstadoDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMOCIONAL`.`Fecha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMOCIONAL`.`Fecha` ;

CREATE TABLE IF NOT EXISTS `EMOCIONAL`.`Fecha` (
  `IdFecha` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fecha` DATE NULL COMMENT '',
  `DiaSemana` VARCHAR(30) NULL COMMENT '',
  PRIMARY KEY (`IdFecha`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMOCIONAL`.`Hora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMOCIONAL`.`Hora` ;

CREATE TABLE IF NOT EXISTS `EMOCIONAL`.`Hora` (
  `idHora` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Hora` VARCHAR(6) NULL COMMENT '',
  PRIMARY KEY (`idHora`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMOCIONAL`.`MemoriaCita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMOCIONAL`.`MemoriaCita` ;

CREATE TABLE IF NOT EXISTS `EMOCIONAL`.`MemoriaCita` (
  `idMemoriaCita` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `SentimientosAngustia` INT NULL COMMENT '',
  `EstresLaboral` INT NULL COMMENT '',
  `IncomodidadLaboral` INT NULL COMMENT '',
  `DepresionLaboral` VARCHAR(45) NULL COMMENT '',
  `ComentariosDoctor` VARCHAR(1000) NULL COMMENT '',
  PRIMARY KEY (`idMemoriaCita`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMOCIONAL`.`EstadoCita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMOCIONAL`.`EstadoCita` ;

CREATE TABLE IF NOT EXISTS `EMOCIONAL`.`EstadoCita` (
  `idEstadoCita` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Estado` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idEstadoCita`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMOCIONAL`.`Cita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMOCIONAL`.`Cita` ;

CREATE TABLE IF NOT EXISTS `EMOCIONAL`.`Cita` (
  `IdCita` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Usuario_IdUsuario` INT NOT NULL COMMENT '',
  `Doctor_IdDoctor` INT NOT NULL COMMENT '',
  `Fecha_IdFecha` INT NOT NULL COMMENT '',
  `Hora_Inicio_idHora` INT NOT NULL COMMENT '',
  `MemoriaCita_idMemoriaCita` INT NOT NULL COMMENT '',
  `Hora_Fin_idHora` INT NOT NULL COMMENT '',
  `EstadoCita_idEstadoCita` INT NOT NULL COMMENT '',
  PRIMARY KEY (`IdCita`, `Usuario_IdUsuario`, `Doctor_IdDoctor`, `Fecha_IdFecha`, `Hora_Inicio_idHora`, `MemoriaCita_idMemoriaCita`, `Hora_Fin_idHora`, `EstadoCita_idEstadoCita`)  COMMENT '',
  INDEX `fk_Cita_Usuario_idx` (`Usuario_IdUsuario` ASC)  COMMENT '',
  INDEX `fk_Cita_Doctor1_idx` (`Doctor_IdDoctor` ASC)  COMMENT '',
  INDEX `fk_Cita_Fecha1_idx` (`Fecha_IdFecha` ASC)  COMMENT '',
  INDEX `fk_Cita_Hora1_idx` (`Hora_Inicio_idHora` ASC)  COMMENT '',
  INDEX `fk_Cita_MemoriaCita1_idx` (`MemoriaCita_idMemoriaCita` ASC)  COMMENT '',
  INDEX `fk_Cita_Hora2_idx` (`Hora_Fin_idHora` ASC)  COMMENT '',
  INDEX `fk_Cita_EstadoCita1_idx` (`EstadoCita_idEstadoCita` ASC)  COMMENT '',
  CONSTRAINT `fk_Cita_Usuario`
    FOREIGN KEY (`Usuario_IdUsuario`)
    REFERENCES `EMOCIONAL`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Doctor1`
    FOREIGN KEY (`Doctor_IdDoctor`)
    REFERENCES `EMOCIONAL`.`Doctor` (`IdDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Fecha1`
    FOREIGN KEY (`Fecha_IdFecha`)
    REFERENCES `EMOCIONAL`.`Fecha` (`IdFecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Hora1`
    FOREIGN KEY (`Hora_Inicio_idHora`)
    REFERENCES `EMOCIONAL`.`Hora` (`idHora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_MemoriaCita1`
    FOREIGN KEY (`MemoriaCita_idMemoriaCita`)
    REFERENCES `EMOCIONAL`.`MemoriaCita` (`idMemoriaCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Hora2`
    FOREIGN KEY (`Hora_Fin_idHora`)
    REFERENCES `EMOCIONAL`.`Hora` (`idHora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_EstadoCita1`
    FOREIGN KEY (`EstadoCita_idEstadoCita`)
    REFERENCES `EMOCIONAL`.`EstadoCita` (`idEstadoCita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
